module.exports = {
  name: 'imagine',
  aliases: ['genimg', 'draw', 'aiimg'],
  description: 'Text se AI image generate karein',
  category: 'AI',
  isOwner: false,
  isAdmin: false,
  isPremium: true,
  run: async (conn, m, args, ctx) => {
    const prompt = args.join(' ');
    if (!prompt) return ctx.fReply(`❌ Usage: ${ctx.prefix}imagine <description>\nExample: ${ctx.prefix}imagine a cat flying in space`);
    
    await ctx.fReply('🎨 *Generating image...* (May take 10-20 seconds)');
    
    try {
      // Free AI image generator API
      const response = await fetch('https://api.yanz.xyz/api/ai/text2img?prompt=' + encodeURIComponent(prompt));
      const data = await response.json();
      
      if (data && data.image) {
        await conn.sendMessage(m.key.remoteJid, { 
          image: { url: data.image }, 
          caption: `🎨 *Prompt:* ${prompt}\n🤖 *Generated by AI*` 
        }, { quoted: m });
      } else {
        await ctx.fReply('❌ Failed to generate image. Try a different prompt.');
      }
    } catch (e) {
      await ctx.fReply('❌ AI Image service unavailable.');
    }
  }
};
